server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:mysql://localhost:3306/goods
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

jwt:
  secret: 4791dae6a6c86b6e7d8fd49e44ef8d7d4b94880609fcda10a55f55045dcddf1471d5ac0aa66417e450d52741a3f6825e49ca983dbd7aad426862ebd1a89e499d
